var game;null==game&&(game={});
(function(){game.qp_a=null;game.qp_b=null;game.qp_c=null;game.qp_d=null;game.qp_e=null;game.qp_f=!1;game.qp_g=[];game.qp_h=[];game.qp_i=0;game.qp_j=null;game.qp_k=[1,2,3,4,5,6,7,8,9];game.qp_l=function(a){for(var b="",d=0;81>d;d++)b=0!=a.charAt(d)?b+game.qp_k[a.charAt(d)-1]:b+"0";console.log("mapping",a,b);return b};game.qp_m=function(a){for(var b=0;8>b;b++){var d=parseInt(Math.random()*(9-b)),c=game.qp_k[d];game.qp_k[d]=game.qp_k[9-b-1];game.qp_k[9-b-1]=c}console.log(game.qp_k);$.getJSON("assets/soduku_"+
a+".txt",function(b){game.qp_f=!1;game.qp_g.length=0;game.qp_h.length=0;game.qp_i=0;game.qp_j=b;var d=b.puzzle=game.qp_l(b.puzzle),c=b.answer=game.qp_l(b.answer);console.log(b.puzzle,b.answer);for(var e=0;9>e;e++){game.qp_h[e]=[];for(var h=0;9>h;h++){var k=game.qp_h[e][h]=new soduku.Qp_n(e,h),f=d.charAt(e+9*h);k.answer=c.charAt(e+9*h);k.status=0==f?soduku.EDIT_NODE:soduku.INIT_NODE;k.setValue(f)}}game.qp_b.setTitle(b.id);window.localStorage.setItem("qipa_soduku"+game.qp_o(),a);window.localStorage.setItem("qipa_soduku_current",
a)})};game.checkLegal=function(a,b,d){for(var c=0;9>c;c++)if(game.qp_h[a][c].status==soduku.INIT_NODE&&game.qp_h[a][c].value==d&&c!=b||game.qp_h[c][b].status==soduku.INIT_NODE&&game.qp_h[c][b].value==d&&c!=a)return!1;for(var l=3*parseInt(a/3),p=3*parseInt(b/3),c=0;3>c;c++)for(var m=0;3>m;m++){var n=l+c,h=p+m;if((n!=a||h!=b)&&game.qp_h[n][h].status==soduku.INIT_NODE&&game.qp_h[n][h].value==d)return!1}return!0};game.qp_o=function(a){null==a&&(a=game.qp_j.id);return parseInt(parseInt(a)/200)};game.qp_p=
function(){var a=(game.qp_j.id+200)%1400;game.qp_o(a);window.localStorage.setItem("qipa_soduku"+game.qp_o(a),a);game.qp_m(a)};game.qp_q=function(){var a=(game.qp_j.id-200)%1400;0>a&&(a+=1400);game.qp_o(a);window.localStorage.setItem("qipa_soduku"+game.qp_o(a),a);game.qp_m(a)};game.qp_r=function(){var a=parseInt((game.qp_j.id+1)%1400);window.localStorage.setItem("qipa_soduku"+game.qp_o(),a);game.qp_m(a)};game.qp_s=function(){game.qp_a.addChild(game.qp_e);game.qp_e.setup()};game.qp_t=function(){for(var a in game.qp_h)for(var b in game.qp_h[a])game.qp_h[a][b].invalidate()};
var b=function(a){if("object"!=typeof a)return a;var e={},d;for(d in a)e[d]=b(a[d]);return e};game.qp_u=function(){game.qp_g.push(b(game.qp_h))};game.qp_v=function(){return game.qp_g.pop()};game.qp_w=function(a){return game.queue.getResult(a)}})();var soduku;null==soduku&&(soduku={});
(function(){function b(a){if(null!=game.qp_b.selectView.parent){var b=game.qp_b.selectView.parent.i,g=game.qp_b.selectView.parent.j;game.qp_h[b][g].status!=soduku.INIT_NODE&&(game.qp_u(),a=parseInt(a.target.label.text),game.qp_f?game.qp_h[b][g].togglePoss(a):game.qp_h[b][g].setValue(a))}}function a(a){null!=game.qp_b.selectView.parent&&(game.qp_u(),game.qp_h[game.qp_b.selectView.parent.i][game.qp_b.selectView.parent.j].setValue())}function e(a){a=game.qp_g.pop();null!=a&&(game.qp_h=a,game.qp_t())}
function d(a){game.qp_f=!game.qp_f;a=game.qp_f?soduku.color.button:soduku.color.frame;var b=game.qp_f?soduku.color.frame:soduku.color.button,g;for(g in game.qp_c.children)g=game.qp_c.getChildAt(g),"num"==g.type&&g.setBackColor(a,b)}function c(){this.initialize();this.x=20;this.y=730;for(var k=[{desc:1,onclick:b,type:"num"},{desc:2,onclick:b,type:"num"},{desc:3,onclick:b,type:"num"},{desc:4,onclick:b,type:"num"},{desc:5,onclick:b,type:"num"},{desc:6,onclick:b,type:"num"},{desc:7,onclick:b,type:"num"},
{desc:8,onclick:b,type:"num"},{desc:9,onclick:b,type:"num"},{desc:"Mark",onclick:d}],f=0;f<k.length;f++){var g=k[f].desc,c=f%5*123+55,h=80*parseInt(f/5)+35,g=new widget.Button(c,h,110,70,g);g.type=k[f].type;g.onClick=k[f].onclick;g.setBackColor(soduku.color.frame,soduku.color.button);this.addChild(g)}k=new widget.Button(0,H-this.y,W/2-30,60,"Clear");k.onClick=a;k.regY=70;k.regX=0;k.setBackColor(soduku.color.frame,soduku.color.button);f=new widget.Button(W-37,H-this.y,W/2-30,60,"Undo");
f.onClick=e;f.regY=70;f.regX=W/2-30;f.setBackColor(soduku.color.frame,soduku.color.button);this.addChild(k,f)}var l=function(){this.initialize();this.bm=new createjs.Shape;this.bm.graphics.beginFill("#ffffff").drawRect(0,0,W,H);this.bm.alpha=0.9;this.addChild(this.bm);this.text=new createjs.Text("Congratulations to pass","bold 100px Arial","black");this.text.x=W/2;this.text.y=150;this.text.regX=this.text.getBounds().width/2;this.text_hard=new createjs.Text("","bold 64px Arial","black");this.text_hard.x=
W/2;this.text_hard.y=400;this.text_id=new createjs.Text("","bold 64px Arial","black");this.text_id.x=W/2;this.text_id.y=500;this.addChild(this.text,this.text_hard,this.text_id);this.next=new widget.Button(W/2,H-100,150,45,"Next level");this.next.setBackColor(soduku.color.frame,soduku.color.button);this.next.onClick=function(a){game.qp_r();game.qp_a.removeChild(game.qp_e)};this.easy=new widget.Button(0,H,150,45,"Easier");this.easy.setBackColor(soduku.color.frame,
soduku.color.button);this.easy.regY=this.easy.getBounds().height;this.easy.regX=0;this.easy.onClick=function(){game.qp_q();game.qp_a.removeChild(game.qp_e)};this.hard=new widget.Button(W,H,150,45,"Harder");this.hard.setBackColor(soduku.color.frame,soduku.color.button);this.hard.regY=this.hard.getBounds().height;this.hard.regX=this.hard.getBounds().width;this.hard.onClick=function(){game.qp_p();game.qp_a.removeChild(game.qp_e)};this.addChild(this.next,this.easy,this.hard);this.setup=
function(){this.text_hard.text=soduku.DIFFICULTY[game.qp_o()];this.text_hard.regX=this.text_hard.getBounds().width/2;this.text_id.text="NO."+game.qp_j.id;this.text_id.regX=this.text_id.getBounds().width/2}};l.prototype=new createjs.Container;var p=function(){this.initialize();this.x=W/2;this.y=H/2-80;this.regY=W/2;this.regX=W/2;this.scaleX=this.scaleY=0.96;var a=new createjs.Shape;a.graphics.beginFill("#949494").drawRect(0,0,W,W);this.addChild(a);this.setupNodeView=function(){for(var a=[],b=0;9>b;b++){a[b]=
[];for(var c=0;9>c;c++)a[b][c]=new soduku.Qp_z(b,c),this.addChild(a[b][c])}this.nodeViews=a};this.setupNodeView();this.title=new createjs.Text("","bold 25px Arial","black");this.title.x=5;this.title.y=-35;this.addChild(this.title);this.setTitle=function(a){this.title.text="NO."+a;this.diff.label.text=soduku.DIFFICULTY[game.qp_o()];this.diff.adjustLabel()};this.diff=new widget.Button(W,-35,150,45,"label");this.diff.setBackColor("#949494","#ffffff");this.diff.regX=this.diff.getBounds().width;this.diff.onClick=
function(){game.qp_p()};this.addChild(this.diff);this.selectView=new createjs.Shape;this.selectView.graphics.beginFill("#dbdbdb").drawRect(0,0,67,67)};p.prototype=new createjs.Container;var m=function(){this.initialize();this.x=2;this.y=-1;this.update=function(a){this.removeAllChildren();for(var b=0;9>b;b++)if(a&1<<b){var c=3+b%3*22,d=2+22*parseInt(b/3),e=new createjs.Text;e.text=b+1;e.font="normal 20px Times New Roman";e.color="black";e.x=c;e.y=d;this.addChild(e)}}};m.prototype=new createjs.Container;
var n=function(a,b){this.initialize();this.i=a;this.j=b;this.mouseChildren=!1;this.node=new createjs.Shape;this.node.graphics.beginFill("#ffffff").drawRect(0,0,67,67);this.x=1.5*a+3*parseInt(a/3)+67*a+10;this.y=1.5*b+3*parseInt(b/3)+67*b+10;this.addChild(this.node);this.num=new createjs.Text;this.num.color="black";this.num.font="normal 49px Arial";this.num.x=20;this.num.y=10;this.num.name="num";this.poss=new soduku.Qp_A;this.poss.name="poss";this.addChild(this.num);this.on("click",function(a){a=a.target;
a.addChildAt(a.parent.selectView,1)});this.setVal=function(a,b){null!=this.getChildByName("poss")&&(this.removeChild(this.poss),this.addChild(this.num));this.num.text=a;this.num.color=b};this.setPoss=function(a){null!=this.getChildByName("num")&&(this.removeChild(this.num),this.addChild(this.poss));this.poss.update(a)}};n.prototype=new createjs.Container;var h=function(a,b){this.x=a;this.y=b;this.poss=0;this.invalidate=function(){0<parseInt(this.value)?game.qp_b.nodeViews[this.x][this.y].setVal(0<
this.value?this.value:"",this.status==soduku.INIT_NODE?"black":game.checkLegal(this.x,this.y,this.value)?"blue":"red"):game.qp_b.nodeViews[this.x][this.y].setPoss(this.poss)};this.setValue=function(a){this.value==this.answer&&a!=this.answer&&game.qp_i--;this.value=a;this.poss=0;this.invalidate();this.value==this.answer&&++game.qp_i>=soduku.NODE_COUNT&&game.qp_s()};this.setPoss=function(a){this.value=0;this.poss=a;this.invalidate()};this.togglePoss=function(a){this.poss^=1<<a-1;this.value=0;this.invalidate()}};
h.prototype={};c.prototype=new createjs.Container;soduku.Qp_B=c;soduku.Qp_n=h;soduku.Qp_y=p;soduku.Qp_z=n;soduku.Qp_A=m;soduku.Qp_x=l;soduku.INIT_NODE=0;soduku.EDIT_NODE=1;soduku.NODE_COUNT=81;soduku.DIFFICULTY="Easy Normal Hard Advanced Master Nightmare Hell".split(" ");soduku.color={background:"#ffffff",button:"#dbdbdb",frame:"#949494"}})();var widget;null==widget&&(widget={});
(function(){var b=function(a,b,d,c,l){this.initialize();this.x=a;this.y=b;this.setBounds(a,b,d,c);this.foreLayer=new widget.Layer;this.textLayer=new widget.Layer;this.backLayer=new widget.Layer;this.addChild(this.backLayer,this.textLayer);a=new createjs.Text(l,"bold 25px Arial","black");a.x=0.5*d;a.y=0.5*c;this.adjustLabel=function(){this.label.regX=0.5*this.label.getBounds().width;this.label.regY=0.5*this.label.getBounds().height};this.label=a;this.adjustLabel();this.textLayer.addChild(a);this.regX=
0.5*this.getBounds().width;this.regY=0.5*this.getBounds().height;this.nativeBack=new createjs.Shape;this.backLayer.addChild(this.nativeBack);this.mouseChildren=!1;this.onClick=null;this.on("click",function(a){if((!createjs.Touch.isSupported()||a.nativeEvent.constructor!=MouseEvent)&&null!=a.target.onClick)a.target.onClick(a)});this.setBackColor=function(a,b){this.nativeBack.graphics.setStrokeStyle(5).beginStroke(a).beginFill(b).drawRect(0,0,d,c,10)}};b.prototype=new createjs.Container;b.prototype.setBackground=
function(a){a=new createjs.Bitmap(a);a.x=0;a.y=0;a.scaleX=this.getBounds().width/a.getBounds().width;a.scaleY=this.getBounds().height/a.getBounds().height;this.backLayer.addChild(a);this.backLayer.removeChild(this.nativeBack)};b.prototype.setPressImage=function(a){this.bmPress=new createjs.Bitmap(a);this.bmPress.x=0;this.bmPress.y=0;this.bmPress.scaleX=this.getBounds().width/this.bmPress.getBounds().width;this.bmPress.scaleY=this.getBounds().height/this.bmPress.getBounds().height};widget.Button=b})();
(function(){var b=function(a,b,d,c,l){this.initialize();this.x=a?a:0;this.y=b?b:0;this.setBounds(a,b,d,c);l&&(this.nativeBack=new createjs.Shape,this.nativeBack.graphics.beginFill(l).drawRect(0,0,d,c),this.addChild(this.nativeBack))};b.prototype=new createjs.Container;b.prototype.setBackground=function(a){a=new createjs.Bitmap(a);a.x=0;a.y=0;a.scaleX=this.getBounds().width/a.getBounds().width;a.scaleY=this.getBounds().height/a.getBounds().height;this.addChild(a)};widget.Layer=b})();var queue;
function loadResource(){SCREEN_SHOW_ALL=!0;var b=new ProgressBar(0.8*W,40);b.regX=b.w/2;b.regY=b.h/2;b.x=W/2;b.y=H/2;stage.addChild(b);queue=game.queue=new createjs.LoadQueue(!1);queue.setMaxConnections(30);loadGameData();queue.on("complete",setup,null,!0);queue.loadManifest({path:RES_DIR+"img/",manifest:[]},!1);b.forQueue(queue);queue.load()}
function setup(){game.qp_a=new widget.Layer(0,0,W,H,"#ffffff");game.qp_b=new soduku.Qp_y(0,W/2,W,W);game.qp_c=new soduku.Qp_B;game.qp_e=new soduku.Qp_x;game.qp_a.addChild(game.qp_b,game.qp_c);stage.addChild(game.qp_a);var b=window.localStorage.getItem("qipa_soduku_current");game.qp_m(null==b?1:b);console.log(W,H)};
